### ISSUE TITLE
Wrong display of polar plot

### ISSUE THREAD

**Issue by vistalba** [mikenye/docker-readsb-protobuf#19]
I can see that the polar plot does display wrong directions:

![image](https://user-images.githubusercontent.com/12324196/107051124-5ca15b80-67cc-11eb-8a54-5af9e56b9e58.png)

If I compare to flightaware and flightradar24:
![image](https://user-images.githubusercontent.com/12324196/107051199-75117600-67cc-11eb-8a18-08df9634b05d.png)

![image](https://user-images.githubusercontent.com/12324196/107051235-8064a180-67cc-11eb-885a-9c6baceb380e.png)

It looks like it is mirrored between West/East? Any ideas why this happens?

**Comment by Vertikar** [comment]
I've got the same issue, but wasn't too worried about it

**Comment by mikenye** [comment]
I'm looking into this.

According to [readsb.proto](https://github.com/Mictronics/readsb-protobuf/blob/a719c8c9e8089352c078dd6ea830c76657f9a14b/readsb.proto#L271), the data is output as `maximum range per bearing, 0 to 359 degree, default resolution 5 degree.`

So, there's 72 range measurements returned by `readsb`. The radar graph plugin starts with the first measurement at "North", then completes graphing the measurements clockwise.

You can see this in Grafana if you edit the panel and set the text size to something greater than zero:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/6915079/107143060-cdcc4480-696d-11eb-94b8-7cd465205752.png">

So, it looks like maybe `readsb` outputs the data anti-clockwise.

I'll see what can be done about this.

**Comment by mikenye** [comment]
Hi All,

I've modified the script that connects the readsb protobuf data to telegraf, to reverse the order of the polar plot point.

Hopefully this will solve the problem.

The change is live in the `latest` version of the container.

Because the query looks at the last 7 days' of data, it will take over 7 days from updating the container for the polar plot to look correct.

Let me know if this fixes the problem.

**Comment by vistalba** [comment]
This works for me. As I only had data for almost 2 days now I just deleted the `polar_plot` stuff and now it looks correct:

![image](https://user-images.githubusercontent.com/12324196/107206174-fcdec680-69fe-11eb-8645-bdb7fd411a22.png)

THX! :D

**Comment by mikenye** [comment]
Thanks for the quick reply!
