### ISSUE TITLE
404 Not Found on Performance Graph Disk I/O - IOPS Disk I/O - Bandwidth

### ISSUE THREAD

**Issue by mo8Zomo0** [mikenye/docker-readsb-protobuf#25]
The Disk IO graphs seem to be broken, they just return a "404 Not Found" 

http://ip:8080/graphs/

Anything missing on my system or is this a bug of the container?

Disk I/O - IOPS
Disk I/O - Bandwidth

<img width="328" alt="Bildschirmfoto 2021-03-16 um 16 03 28" src="https://user-images.githubusercontent.com/2004752/111331445-32677700-8671-11eb-930e-876bb08c728e.png">

http://ip:8080/graphs/images/system-disk_io_octets-24h.png?time=1615906706.622
http://ip:8080/graphs/images/system-disk_io_iops-24h.png?time=1615906706.622

**Comment by mo8Zomo0** [comment]
I also noticed that the week/month/year graphs (all) are broken. Is is not running for so long but I would have expected it to show at least the current data instead of broken images.
sample image uri which fails (ip = ipaddress of the docker host)
http://ip:8080/graphs/images/readsb-local_trailing_rate-30d.png?time=1615908233.056

<img width="1116" alt="Bildschirmfoto 2021-03-16 um 16 23 41" src="https://user-images.githubusercontent.com/2004752/111334680-10232880-8674-11eb-9a7a-6c179936c84d.png">

**Comment by mikenye** [comment]
Sorry for the delay in getting back to you.

This is an artifact of running inside a container. There are probably system capabilities you could add to the container to allow this to work.
