### ISSUE TITLE
Influxdb reconnection failures

### ISSUE THREAD

**Issue by visibilityspots** [mikenye/docker-readsb-protobuf#27]
Seems like I'm having the issue as described over here: https://github.com/influxdata/telegraf/issues/5905 I tried to run the container using the environment parameter through docker but that wasn't a success :( 

I'm wondering in which file I should add this GODEBUG=http2client=0 parameter to test if this solves the issue with influxdb reconnecting behind a proxy like traefik

**Comment by mikenye** [comment]
Hi Jan,

I created branch issue_27 and set the variable: https://github.com/mikenye/docker-readsb-protobuf/blob/a87f0aa9c78fd840c76f287d9b6b715d74733f9e/rootfs/etc/services.d/telegraf/run#L9

Are you able to build and test?

-M

**Comment by visibilityspots** [comment]
I've builded the image and running as we speak, will keep an eye on it and try to reproduce the issue to see if it fixed the interrupts. Will keep you posted!

**Comment by visibilityspots** [comment]
it didn't worked, but I have now a branch to play upon, will try some stuff and let you now when I got it fixed hopefully!

**Comment by mikenye** [comment]
No worries, let me know if I can help.

**Comment by mo8Zomo0** [comment]
btw, is there a guide setting up grafana with readsb, did not see much in https://mikenye.gitbook.io/ads-b/?q=grafana

**Comment by mikenye** [comment]
@mo8Zomo0 currently no - I've been meaning to write one, however in the meantime InfluxDB v2 has been released, and it is completely different to v1. If you join the Discord server and message me, I would be happy to talk you through the process for InfluxDB v1.8, however I don't really want to spend the time documenting it, only to have to re-do it for v2... :)

**Comment by mikenye** [comment]
@mo8Zomo0 you might also want to check out: https://grafana.com/grafana/dashboards/13168

It only works with InfluxDB v1.x, but might be useful to you.

**Comment by andye2801** [comment]
Hello! Stumbled across this issue, I've been meaning to fix my output to InfluxDB to get my Grafan Dashboard working again after my container for InfluxDB updated to 2.0.

Are you working on the new connection to InfluxDB2.0 or is it worth my pinning my InfluxDB container to 1.8 and using the existing output for InfluxDB?

**Comment by mikenye** [comment]
Just following up on this. InfluxDB v2.x support was added in #44.

**Comment by visibilityspots** [comment]
to me this issue can be closed since I switched to prometheus.
