### ISSUE TITLE
Question: how to use kalibrate?

### ISSUE THREAD

**Issue by klara31** [mikenye/docker-readsb-protobuf#3]
I saw that you added rtl-kalibrate to the container, but how do I use that feature properly?

**Comment by mikenye** [comment]
Hi @klara31,

I was wondering about how to determine the PPM figure for my radio, and I came across this <https://discussions.flightaware.com/t/setting-frequency-offset-or-exact-frequency-ppm/15812/6>.

I haven't had time to try this myself yet, however I had planned to try this and document the process in the container's README.

You'll have to stop the container, and then run the container changing the entrypoint to a shell, eg:

```
docker stop readsb
docker run --rm -it -d /dev/bus/usb --entrypoint bash mikenye/readsb-protobuf
```

You should then be able to run the commands as-per the flightaware link above.

Bear in mind that the flightaware blue dongles have a built in 1090MHz bandpass filter, so I'm not sure whether the process will even work...

Let me know how you go.

**Comment by mikenye** [comment]
How did you go with this?

**Comment by klara31** [comment]
Haven't got the time yet to give it a try. And as I just switched: readsb is still determining the gain...
I'll let you know!

**Comment by klara31** [comment]
It works. Small note: the command should be:
```docker run --rm -it --device /dev/bus/usb --entrypoint bash mikenye/readsb-protobuf```

**Comment by mikenye** [comment]
Fixed, thanks!
