### ISSUE TITLE
Feature Request: Prometheus 

### ISSUE THREAD

**Issue by JRascagneres** [mikenye/docker-readsb-protobuf#30]
I know you currently have InfluxDB support but with that in mind it'd be really nice to get prometheus intregration. Based on the current support for influxdb I wouldn't expect this would be too bad to add.

**Comment by mikenye** [comment]
Implemented! Sorry for the wait.

**Comment by JRascagneres** [comment]
> Implemented! Sorry for the wait.

Wow thanks 😄
