### ISSUE TITLE
Feature Request: Add variable to allow setting of Telegraf hostname

### ISSUE THREAD

**Issue by psfshr** [mikenye/docker-readsb-protobuf#32]
Currently Telegraf appears to pick up the container ID as the hostname when logging to InfluxDB. As the ID changes when the container is redeployed, this causes the hostname in Influx DB to change when the container is updated. Can a variable be added to give the option to set the Telegraf hostname to a fixed value which then persists across container instances.

**Comment by hakan42** [comment]
You can set the hostname of the container via "docker run --hostname=foobar". In docker-compose, the same is also possible:

https://stackoverflow.com/a/63291253/166670

**Comment by psfshr** [comment]
So I'm actually using Ansible to do the container management, but just re-reading the docs there's an explicit Ansible property to set the hostname and domain name, so I'll try those.
